version: "3.8"
services:
  app:
    build:
      context: .
    env_file: .env
    container_name: feedback_bot
    command: [ "sh", "./docker/app.sh" ]
    volumes:
      - .:/feedback_bot
    restart: unless-stopped
